set -g history-limit 50000

set -g mouse on

setw -g mode-keys vi

set -g base-index 1
setw -g pane-base-index 1

set -sg escape-time 10

# Do not rely on terminal clipboard escape sequences.
set -g set-clipboard off

# 再接続時に、現在のデスクトップの環境を取り込む
set -ag update-environment " DISPLAY XAUTHORITY WAYLAND_DISPLAY XDG_SESSION_TYPE XDG_RUNTIME_DIR"

# コピーするたびにWayland／X11を判定する
set -s copy-command 'if [ "$XDG_SESSION_TYPE" = "wayland" ]; then \
    wl-copy; \
else \
    xclip -selection clipboard -in >/dev/null; \
fi'

bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel

# Change prefix from <C-b> to <C-a>
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g status-style 'bg=terminal, fg=terminal'
